In [246]:
# setup
import numpy as np

cards = np.loadtxt('day04-input.txt',skiprows=2)
testcards = np.loadtxt('day04-test.txt',skiprows=2)
clues = np.loadtxt('day04-input.txt',max_rows=1,delimiter=',')

In [247]:
# Part 1: determine the first board to win bingo and compute that boards final score

def prob():
    bingobook = np.zeros_like(cards)
    lim = [0,1,2,3,4]
    columncheck = np.arange(0,499,5)

    for i in range(len(clues)):
        for j in range(len(bingobook)):
            for k in lim:
                if cards[j,k] == clues[i]:
                    bingobook[j,k] = 1
        for j in range(len(bingobook)):
            if np.sum(bingobook[j,0:5]) == 5:
                bingobook[j] = 0
        for l in columncheck:
            rowend = l+5
            for m in lim:
                if np.sum(bingobook[l:rowend,m]) == 5:
                    bingobook[l:rowend,m] = 0
    return

prob()
            
winningclue = 77
sum = 6 + 26 + 75 + 61 + 38 + 20 + 56 + 70 + 82 + 76 + 29
solution = winningclue*sum
print('Part 1 Solution = ',solution)

# winning row 319
# winning card at time of 77
#[0. 0. 1. 1. 0.]
#[0. 1. 1. 0. 0.]
#[1. 0. 0. 1. 0.]
#[1. 0. 1. 1. 0.]

Part 1 Solution =  41503


In [248]:
# Part 2 Solution - Determine last board to bingo

# Function to create deck
def formdeck(array):
    board = np.zeros((5,5))
    cards_array = np.asarray(array)
    cardjump = np.arange(0,499,5)
    cardnum = 0
    deck = [None]*100
    
    for i in cardjump:
        k = 0
        for j in range(len(board)):
            board[j] = cards_array[i+k]
            k += 1
        deck[cardnum] = board
        cardnum += 1
        board = np.zeros((5,5))
    return(deck)

# Part 2 solution function        
def prob2(array):
    deck = formdeck(array)
    cardstep = np.arange(0,100,1)
    bingobook = np.zeros_like(deck)
    lim = [0,1,2,3,4]
    
    for i in range(len(clues)):
        # mark clue
        for j in range(len(cardstep)):
            n = cardstep[j]
            board = deck[n]
            mirror = bingobook[n]
            for k in lim:
                for l in lim: 
                    if board[k,l] == clues[i]:
                        mirror[k,l] = 1
            bingobook[n] = mirror
        if i == 85:
            return(clues[i],bingobook[cardstep],cardstep)
        for j in range(len(cardstep)):
            n = cardstep[j]
            mirror = bingobook[n]
            mirrorT = np.transpose(mirror)
            for k in lim:
                found = False
                if np.sum(mirror[k]) == 5:
                    cardstep[j] = 101
                if np.sum(mirrorT[k]) == 5:
                    cardstep[j] = 101
        cardstep = list(filter((101).__ne__, cardstep))      
    return(print('no winner'))    

clue, markers, step = prob2(cards)
sums = 81+75+24+46+1
solution = clue*sums
print('Part 2 Solution = ', solution)

# Solution = 3178, confirmed 12/9/2021

Part 2 Solution =  3178.0
